#pragma once

#define CARD_BACK_SPRITE "res/cards/CardBack.png"

#define ACE_OF_SPADES_SPRITE "res/cards/AceOfSpades.png"
#define TWO_OF_SPADES_SPRITE "res/cards/TwoOfSpades.png"
#define THREE_OF_SPADES_SPRITE "res/cards/ThreeOfSpades.png"
#define FOUR_OF_SPADES_SPRITE "res/cards/FourOfSpades.png"
#define FIVE_OF_SPADES_SPRITE "res/cards/FiveOfSpades.png"
#define SIX_OF_SPADES_SPRITE "res/cards/SixOfSpades.png"
#define SEVEN_OF_SPADES_SPRITE "res/cards/SevenOfSpades.png"
#define EIGHT_OF_SPADES_SPRITE "res/cards/EightOfSpades.png"
#define NINE_OF_SPADES_SPRITE "res/cards/NineOfSpades.png"
#define TEN_OF_SPADES_SPRITE "res/cards/TenOfSpades.png"
#define JACK_OF_SPADES_SPRITE "res/cards/JackOfSpades.png"
#define QUEEN_OF_SPADES_SPRITE "res/cards/QueenOfSpades.png"
#define KING_OF_SPADES_SPRITE "res/cards/KingOfSpades.png"

#define ACE_OF_HEARTS_SPRITE "res/cards/AceOfHearts.png"
#define TWO_OF_HEARTS_SPRITE "res/cards/TwoOfHearts.png"
#define THREE_OF_HEARTS_SPRITE "res/cards/ThreeOfHearts.png"
#define FOUR_OF_HEARTS_SPRITE "res/cards/FourOfHearts.png"
#define FIVE_OF_HEARTS_SPRITE "res/cards/FiveOfHearts.png"
#define SIX_OF_HEARTS_SPRITE "res/cards/SixOfHearts.png"
#define SEVEN_OF_HEARTS_SPRITE "res/cards/SevenOfHearts.png"
#define EIGHT_OF_HEARTS_SPRITE "res/cards/EightOfHearts.png"
#define NINE_OF_HEARTS_SPRITE "res/cards/NineOfHearts.png"
#define TEN_OF_HEARTS_SPRITE "res/cards/TenOfHearts.png"
#define JACK_OF_HEARTS_SPRITE "res/cards/JackOfHearts.png"
#define QUEEN_OF_HEARTS_SPRITE "res/cards/QueenOfHearts.png"
#define KING_OF_HEARTS_SPRITE "res/cards/KingOfHearts.png"

#define ACE_OF_DIAMONDS_SPRITE "res/cards/AceOfDiamonds.png"
#define TWO_OF_DIAMONDS_SPRITE "res/cards/TwoOfDiamonds.png"
#define THREE_OF_DIAMONDS_SPRITE "res/cards/ThreeOfDiamonds.png"
#define FOUR_OF_DIAMONDS_SPRITE "res/cards/FourOfDiamonds.png"
#define FIVE_OF_DIAMONDS_SPRITE "res/cards/FiveOfDiamonds.png"
#define SIX_OF_DIAMONDS_SPRITE "res/cards/SixOfDiamonds.png"
#define SEVEN_OF_DIAMONDS_SPRITE "res/cards/SevenOfDiamonds.png"
#define EIGHT_OF_DIAMONDS_SPRITE "res/cards/EightOfDiamonds.png"
#define NINE_OF_DIAMONDS_SPRITE "res/cards/NineOfDiamonds.png"
#define TEN_OF_DIAMONDS_SPRITE "res/cards/TenOfDiamonds.png"
#define JACK_OF_DIAMONDS_SPRITE "res/cards/JackOfDiamonds.png"
#define QUEEN_OF_DIAMONDS_SPRITE "res/cards/QueenOfDiamonds.png"
#define KING_OF_DIAMONDS_SPRITE "res/cards/KingOfDiamonds.png"

#define ACE_OF_CLUBS_SPRITE "res/cards/AceOfClubs.png"
#define TWO_OF_CLUBS_SPRITE "res/cards/TwoOfClubs.png"
#define THREE_OF_CLUBS_SPRITE "res/cards/ThreeOfClubs.png"
#define FOUR_OF_CLUBS_SPRITE "res/cards/FourOfClubs.png"
#define FIVE_OF_CLUBS_SPRITE "res/cards/FiveOfClubs.png"
#define SIX_OF_CLUBS_SPRITE "res/cards/SixOfClubs.png"
#define SEVEN_OF_CLUBS_SPRITE "res/cards/SevenOfClubs.png"
#define EIGHT_OF_CLUBS_SPRITE "res/cards/EightOfClubs.png"
#define NINE_OF_CLUBS_SPRITE "res/cards/NineOfClubs.png"
#define TEN_OF_CLUBS_SPRITE "res/cards/TenOfClubs.png"
#define JACK_OF_CLUBS_SPRITE "res/cards/JackOfClubs.png"
#define QUEEN_OF_CLUBS_SPRITE "res/cards/QueenOfClubs.png"
#define KING_OF_CLUBS_SPRITE "res/cards/KingOfClubs.png"