#pragma once

#define SPADES 1
#define HEARTS 2
#define DIAMONDS 3
#define CLUBS 4

#define ACE_OF_SPADES 10
#define TWO_OF_SPADES 11
#define THREE_OF_SPADES 12
#define FOUR_OF_SPADES 13
#define FIVE_OF_SPADES 14
#define SIX_OF_SPADES 15
#define SEVEN_OF_SPADES 16
#define EIGHT_OF_SPADES 17
#define NINE_OF_SPADES 18
#define TEN_OF_SPADES 19
#define JACK_OF_SPADES 20
#define QUEEN_OF_SPADES 21
#define KING_OF_SPADES 22

#define ACE_OF_HEARTS 23
#define TWO_OF_HEARTS 24
#define THREE_OF_HEARTS 25
#define FOUR_OF_HEARTS 26
#define FIVE_OF_HEARTS 27
#define SIX_OF_HEARTS 28
#define SEVEN_OF_HEARTS 29
#define EIGHT_OF_HEARTS 30
#define NINE_OF_HEARTS 31
#define TEN_OF_HEARTS 32
#define JACK_OF_HEARTS 33
#define QUEEN_OF_HEARTS 34
#define KING_OF_HEARTS 35

#define ACE_OF_DIAMONDS 36
#define TWO_OF_DIAMONDS 37
#define THREE_OF_DIAMONDS 38
#define FOUR_OF_DIAMONDS 39
#define FIVE_OF_DIAMONDS 40
#define SIX_OF_DIAMONDS 41
#define SEVEN_OF_DIAMONDS 42
#define EIGHT_OF_DIAMONDS 43
#define NINE_OF_DIAMONDS 44
#define TEN_OF_DIAMONDS 45
#define JACK_OF_DIAMONDS 46
#define QUEEN_OF_DIAMONDS 47
#define KING_OF_DIAMONDS 48

#define ACE_OF_CLUBS 49
#define TWO_OF_CLUBS 50
#define THREE_OF_CLUBS 51
#define FOUR_OF_CLUBS 52
#define FIVE_OF_CLUBS 53
#define SIX_OF_CLUBS 54
#define SEVEN_OF_CLUBS 55
#define EIGHT_OF_CLUBS 56
#define NINE_OF_CLUBS 57
#define TEN_OF_CLUBS 58
#define JACK_OF_CLUBS 59
#define QUEEN_OF_CLUBS 60
#define KING_OF_CLUBS 61